# Reusable service for memcache cache for use in generic.php and plaformsh.php on demand
#
# For further reading on setup with eZ Platform and Memcached:
# https://doc.ezplatform.com/en/latest/guide/persistence_cache/#memcached
services:
    cache.memcached:
        parent: cache.adapter.memcached
        tags:
            - name: cache.pool
              clearer: cache.app_clearer
              # Example from vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php:
              # memcached://user:pass@localhost?weight=33'
              provider: 'memcached://%cache_dsn%'
              # Cache namespace prefix overriding the one used by Symfony globally
              # This makes sure cache is reliably shared across whole cluster and all Symfony env's
              # Can be used for blue/green deployment strategies when changes affect content cache.
              # For multi db setup adapt this to be unique per pool (one pool per database)
              # If you prefer default behaviour set this to null or comment out, and consider for instance:
              # https://symfony.com/doc/current/reference/configuration/framework.html#prefix-seed
              namespace: '%cache_namespace%'
