imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:             ~
    translator:      { fallback: %locale_fallback% }
    # The secret parameter is used to generate CSRF tokens
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection:
        enabled: true
        # Note: changing this will break legacy extensions that rely on the default name to alter AJAX requests
        # See https://jira.ez.no/browse/EZP-20783
        field_name: ezxform_token
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'eztpl'] } #assets_version: SomeVersionScheme
    trusted_proxies: ~
    session:         ~
        # The session name defined here will be overridden by the one defined in your ezpublish.yml, for your siteaccess.
        # Defaut session name is "eZSESSID{siteaccess_hash}" (unique session name per siteaccess).
        # See ezpublish.yml.example for an example on how to configure this.
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ eZDemoBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/../ezpublish_legacy

parameters:
