imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi: ~
    fragments: ~
    translator:      { fallback: %locale_fallback% }
    # The secret parameter is used to generate CSRF tokens
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'eztpl'] } #assets_version: SomeVersionScheme
    session: ~
        # The session name defined here will be overridden by the one defined in your ezpublish.yml, for your siteaccess.
        # Defaut session name is "eZSESSID{siteaccess_hash}" (unique session name per siteaccess).
        # See ezpublish.yml.example for an example on how to configure this.

assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/../ezpublish_legacy

parameters:
