ezpublish:
    repositories:
        # "default" repository, with default values for storage
        # Same as:
        # default:
        #     storage:
        #         engine: legacy
        #         connection: default
        #     search:
        #         engine: %search_engine%
        #         connection: default
        default:
            storage: ~
            search:
                engine: %search_engine%
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [site]
        groups:
            site_group: [site]
        default_siteaccess: site
        match:
            URIElement: 1

    system:
        site_group:
            languages: [eng-GB]
