overblog_graphql:
    definitions:
        mappings:
            auto_discover: false
            types:
                -   type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
