language: php

# run tests on php 5.5 only and let unit / integration tests deal with php differences
php:
  - 5.5

# list of paths/bundle to execute
env:
    # run setup wizard to install Demo+Content and then test demo with content
  - INSTALL="demoContentNonUniqueDB" PROFILE="demo" TEST="content"
    # test Legacy
  - INSTALL="demoCleanNonUniqueDB" PROFILE="legacyAdmin" TEST="full"
    # test REST
  - INSTALL="demoCleanNonUniqueDB" PROFILE="rest" TEST="fullJson"
  - INSTALL="demoCleanNonUniqueDB" PROFILE="rest" TEST="fullXml"


# test only master (+ Pull requests)
branches:
  only:
    - master

# install packages
before_install:
  - ./bin/.travis/prepare_system.sh
  - ./bin/.travis/prepare_sahi.sh
#  - ./bin/.travis/prepare_selenium2.sh

# setup requirements for running tests
before_script:
  # Prepare eZ Publish (composer, permissions, assets, cache warmup)
  - ./bin/.travis/prepare_ezpublish.sh
  # since setup wizard need to actually work to the other test suites to pass
  # moved it to before_script so that the random timeout on package fetching 
  # don't fail travis
  - php bin/behat --profile setupWizard --suite $INSTALL

# execute behat as the script command
script:
  - php bin/behat --profile $PROFILE --suite $TEST

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
