sudo: required
dist: trusty
language: generic

services:
  - docker

env:
  # list of behat arguments to test
  matrix:
    - ARGS="--profile=rest --suite=fullJson"
    - ARGS="--profile=rest --suite=fullXml"
    - ARGS="--profile=core"

# test only master (+ Pull requests)
branches:
  only:
    - master
    - "1.3"

# Update Docker Composee to 1.5.2 (basic variable substituation, while still supporting Docker 1.8.2 as used by travis)
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  # TODO: For deployment we would need to build & test against prod env for builds, need to balance that against debug ci needs
  - export $(cat bin/.docker/behat.env | xargs)
  - export COMPOSE_FILE="bin/.docker/docker-compose.yml"
  # Build (first generate what we want in php image to check requriments, then build it in a plain volume image)
  - docker run -v `pwd`:/var/www -w /var/www -e SYMFONY_ENV ezsystems/php:7.0-v0.4 /bin/sh -c "
      composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09";
      composer install --no-progress --no-interaction --prefer-dist"
  - ./bin/.docker/build_volume.sh ezsystems/ezplatform_volume:latest
  # Run (start contianers, execute install command and dump assets)
  - docker-compose up -d --no-recreate
  # Install using www-data user, otherwise cache folders will be created with ez users
  - travis_retry docker-compose run -u www-data --rm phpfpm1 /bin/sh -c "php /scripts/wait_for_db.php; php app/console ezplatform:install clean"
  # Output running contianers for debug
  - docker ps

# execute behat as the script command
# using behat.yml which is a copy of behat.yml.dist with hostnames update by docker-compose.yml
script:
  # Need to run as www-data as cache/log files are owned by it TODO: Fix dual user permissions
  - docker-compose run -u www-data --rm behatphpcli bin/behat -vv $ARGS --tags=~@broken

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
