sudo: required
dist: trusty
language: generic

services:
  - docker

env:
  global:
    - COMPOSE_FILE="doc/docker-compose/prod.yml:doc/docker-compose/dev.yml:doc/docker-compose/selenium.yml"
  # list of behat arguments to test
  matrix:
    - ARGS="--profile=rest --suite=fullJson" COMPOSE_FILE="doc/docker-compose/prod.yml:doc/docker-compose/selenium.yml"
    - ARGS="--profile=rest --suite=fullXml" SYMFONY_ENV=behat SYMFONY_DEBUG=1 RUN_INSTALL=1
    - ARGS="--profile=core" SYMFONY_ENV=behat SYMFONY_DEBUG=1 RUN_INSTALL=1

# test only master (+ Pull requests)
branches:
  only:
    - master
    - "1.3"

# Update Docker and Docker Compose
before_install: ./bin/.travis/trusty_update_docker.sh

before_script:
  # Internal auth token dedicated to testing with travis+composer on ezsystems repos, not for reuse!
  - echo "{\"github-oauth\":{\"github.com\":\"d0285ed5c8644f30547572ead2ed897431c1fc09\"}}" > auth.json
  # In case of dev mode we'll need to install composer packages first
  - if [ "$RUN_INSTALL" = "1" ]; then docker-compose -f doc/docker-compose/install.yml up install; fi
  # Run (start containers and execute install command)
  - docker-compose up -d
  #- docker ps
  #- docker-compose logs app
  - travis_retry docker-compose exec --user www-data app /bin/sh -c "php /scripts/wait_for_db.php; php app/console ezplatform:install clean"

# execute behat as the script command
# using behat.yml which is a copy of behat.yml.dist with hostnames update by docker-compose.behat.yml
script: docker-compose run -u www-data --rm behatphpcli bin/behat -vv $ARGS --tags=~@broken

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
