sudo: required
dist: trusty
language: generic

services:
  - docker

env:
  # list of behat arguments to test
  matrix:
    - ARGS="--profile=rest --suite=fullJson"
    - ARGS="--profile=rest --suite=fullXml"
    - ARGS="--profile=core"

# test only master (+ Pull requests)
branches:
  only:
    - master
    - "1.3"

# Update Docker and Docker Compose
before_install: ./bin/.docker/trusty_update_docker.sh

before_script:
  # Internal auth token dedicated to testing with travis+composer on ezsystems repos, not for reuse.
  - echo "{\"github-oauth\":{\"github.com\":\"d0285ed5c8644f30547572ead2ed897431c1fc09\"}}" > ~/.composer/auth.json
  # Build
  - ./bin/.docker/build_volume.sh ezsystems/ezplatform_volume:latest
  # docker-compose only reads .env file from folder it is executed from, so we change folder
  - cd ./bin/.docker/
  - export COMPOSE_FILE="docker-compose.yml:docker-compose.behat.yml"
  # Run (start contianers, execute install command and dump assets)
  - docker-compose up -d --no-recreate
  - travis_retry docker-compose run -u ez --rm phpfpm /bin/sh -c "php /scripts/wait_for_db.php; php app/console ezplatform:install clean"
  # Output running contianers for debug
  - docker ps

# execute behat as the script command
# using behat.yml which is a copy of behat.yml.dist with hostnames update by docker-compose.yml
script: docker-compose run -u ez --rm behatphpcli bin/behat -vv $ARGS --tags=~@broken

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
