language: php

# run tests on php 5.4 only and let unit / integration tests deal with php differences
php:
  - 5.5

# list of paths/bundle to execute
env:
    # run setup wizard to install Demo+Content and then test demo with content
  - INSTALL="installdemocontent" PROFILE="democontent"
    # test REST
  - INSTALL="installdemoclean" PROFILE="restapi"


# test only master (+ Pull requests)
branches:
  only:
    - master

# install packages
before_install:
  - ./bin/.travis/prepare_system.sh
  - ./bin/.travis/prepare_sahi.sh
#  - ./bin/.travis/prepare_selenium2.sh

# setup requirements for running tests
before_script:
  - ./bin/.travis/prepare_ezpublish.sh

# execute behat as the script command
script:
    - php bin/behat --profile $INSTALL
    - php bin/behat --profile $PROFILE

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
