dist: trusty
language: php
php:
  - 7.1

services:
  - docker

env:
  global:
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
    - SYMFONY_ENV=behat
    - SYMFONY_DEBUG=1

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

# test only master (+ Pull requests)
branches:
  only:
    - master
    - /^\d.\d+$/
    # build tags (vX.Y.Z)
    - /^v\d+.\d+.\d+$/

# list of behat arguments to test
matrix:
  include:
    # TMP disable usage of varnish until we figure out segmentation faulty issue on 2.0
    #- TEST_CMD="--mode=behat --profile=rest --suite=fullJson --tags=~@broken" COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/varnish.yml:doc/docker/selenium.yml" WEB_HOST="varnish"
    - name: "PHP Unit tests"
      env:
        - TEST_CMD="php bin/phpunit -v vendor/ezsystems/ezpublish-kernel/eZ/Bundle/EzPublishRestBundle/Tests/Functional"
        - SYMFONY_CMD="ez:behat:create-language 'pol-PL' 'Polish (polski)'"
    - name: "Kernel Rest fullJson tests"
      env: BEHAT_OPTS="--mode=behat --profile=rest --suite=fullJson --tags=~@broken --non-strict"
    - name: "Kernel Rest fullXML tests"
      env: BEHAT_OPTS="--mode=behat --profile=rest --suite=fullXml --tags=~@broken --non-strict"
    - name: "Kernel Rest core tests"
      env: BEHAT_OPTS="--mode=behat --profile=core --tags=~@broken"
    - name: "Behat"
      env: BEHAT_OPTS="--mode=behat --profile=behat --tags=~@broken"
    - name: "Repository Forms tests on Clean Platform"
      env: BEHAT_OPTS="--mode=behat --profile=repository-forms --tags=~@broken --non-strict"
    - name: "Admin UI on Clean Platform"
      env: BEHAT_OPTS="--profile=adminui --suite=adminui"
    - name: "Admin UI on Clean Platform with Varnish and Redis"
      env:
        - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/varnish.yml:doc/docker/redis.yml:doc/docker/selenium.yml"
        - BEHAT_OPTS="--profile=adminui --suite=adminui"
        - WEB_HOST="varnish"
    - if: type in (cron, api)
      name: "Admin UI tests using different personas"
      env:
        - SETUP_BEHAT_OPTS="--profile=setup --suite=personas --tags=@setup"
        - BEHAT_OPTS="--profile=adminui --suite=personas"

# reduce depth (history) of git checkout
git:
  depth: 30

notifications:
  slack:
    rooms:
      - secure: ESkZY5bzNWua0eHc9rBkuE7AZrCNzLeCV1Rtn97h9KIBeuxsiB3heDUAOi3xZkqO4AyKD5AitAM2k7dTdQKvC8WMooHFWFdjlsSepUvjJISy8keY9kiXywUJ1S/YCwMPwT+HAWB4Qk2zyKmlLmZ8IfAK5aBtndXFQFQCqyeW4PE=
      - secure: NlXxYbeVV7mWDTUgeFK0VrUdXGBF4lPVpMLZ3WXYDTUWfFyM8tiChENo/u/9n7tSz6KIxdWpy0j7h8+EjVUVCGxS+4q+kdzkfm1Vwq3ANhMsGBDcwdm7gYWhdd43aXV9ZaZPVUWv5C3yizzmYXeuNtviFDA5DEvrE5Rdp6sBsRE=
    on_success: change
    on_failure: always
    on_pull_requests: false

before_install:
  # Update Docker and Docker Compose
  - ./bin/.travis/trusty/update_docker.sh
  # Internal auth token dedicated to testing with travis+composer on ezsystems repos, not for reuse!
  - echo "{\"github-oauth\":{\"github.com\":\"d0285ed5c8644f30547572ead2ed897431c1fc09\"}}" > auth.json
  # Disable XDebug for performance
  - phpenv config-rm xdebug.ini
  # Get latest composer build
  - travis_retry composer selfupdate
  # Avoid memory issues on composer install
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  # Setup eZ Platform inside docker container
  - /bin/bash ./bin/.travis/trusty/setup_ezplatform.sh "${COMPOSE_FILE}"

before_script:
  # Execute Symfony command if injected into test matrix
  - if [ "${SYMFONY_CMD}" != "" ] ; then docker-compose exec --user www-data app sh -c "bin/console ${SYMFONY_CMD}" ; fi
  - if [ "${SETUP_BEHAT_OPTS}" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/ezbehat $SETUP_BEHAT_OPTS" ; fi
  #- docker ps
  #- docker-compose logs

# Execute test command, need to use sh to get right exit code (docker/compose/issues/3379)
# Behat will use behat.yml which is a copy of behat.yml.dist with hostnames update by doc/docker/selenium.yml
script:
  - if [ "${TEST_CMD}" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "$TEST_CMD" ; fi
  - if [ "${BEHAT_OPTS}" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/ezbehat $BEHAT_OPTS" ; fi


after_failure:
  # Will show us the last bit of the log of container's main processes
  # (not counting shell process above running php and behat)
  # NOTE: errors during docker setup of travis build won't show up here (can't output all as it is too much in debug/verbose mode)
  - docker-compose logs -t --tail=15
  # Will show us what is up, and how long it's been up
  - docker ps -s
