imports:
    - { resource: default_parameters.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: env/docker.php }
    - { resource: env/platformsh.php }

# Configuration for Database connection, can have several connections used by eZ Repositories in ezplatform.yml
doctrine:
    dbal:
        connections:
            default:
                driver: "%database_driver%"
                host: "%database_host%"
                port: "%database_port%"
                user: "%database_user%"
                password: "%database_password%"
                dbname: "%database_name%"
                charset: UTF8

# Base configuration for Solr, for more options see: https://doc.ez.no/display/EZP/Solr+Search+Engine+Bundle
# Can have several connections used by each eZ Repositories in ezplatform.yml
ez_search_engine_solr:
    endpoints:
        endpoint0:
            dsn: "%solr_dsn%"
            core: collection1
    connections:
        default:
            entry_endpoints:
                - endpoint0
            mapping:
                default: endpoint0

framework:
    esi:             ~
    translator:      { fallback: "%locale_fallback%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    csrf_protection: ~
    form:            ~
    validation:      { enable_annotations: true }
    # Place "eztpl" engine first intentionnally.
    # This is to avoid template name parsing with Twig engine, refusing specific characters
    # which are valid with legacy tpl files.
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale_fallback%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        # Note: eZ Publish also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: https://doc.ez.no/display/DEVELOPER/Sessions
    fragments:       ~
    http_method_override: true
    assets: true
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
