framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    # The secret parameter is used to generate CSRF tokens
    secret:          058e7bdb3356d1e126041796db3b7371
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
#    session:
#        auto_start:     true

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/ezpublish_legacy

parameters:
    ezpublish.api.storage_engine.default: legacy
    ezpublish.api.storage_engine.legacy.dsn: mysql://root:root@localhost/ezdemo

    # Siteaccess matching, this is dummy configuration for tests
    ezpublish.siteaccess.default: ezdemo_site
    ezpublish.siteaccess.config:
        Map\URI:
            ezdemo_site: ezdemo_site
            ezdemo_site_admin: ezdemo_site_admin
        Map\Host:
            ezpublish: ezdemo_site
            ezpublish.admin: ezdemo_site_admin
