# This file contains defaults for optional parameters, which you can override in parameters.yml
parameters:
    locale_fallback: en

    # A secret key that's used to generate certain security-related tokens
    secret: '%env(SYMFONY_SECRET)%'

    # Settings for database backend used by Doctrine DBAL
    # In turn used for default storage engine & default search engine (if legacy is configured as search engine)
    database_driver: '%env(DATABASE_DRIVER)%'
    database_host: '%env(DATABASE_HOST)%'
    database_port: '%env(DATABASE_PORT)%'
    database_name: '%env(DATABASE_NAME)%'
    database_user: '%env(DATABASE_USER)%'
    database_password: '%env(DATABASE_PASSWORD)%'
    database_charset: '%env(DATABASE_CHARSET)%'
    # collation currently has effect on MySQL only
    database_collation: '%env(DATABASE_COLLATION)%'
    # Needed by Doctrine Bundle / ORM to avoid it opening connection during situations where there is no service yet.
    # See: https://symfony.com/doc/current/reference/configuration/doctrine.html
    database_version: '%env(DATABASE_VERSION)%'

    # Setting for mail system, used by SwiftMailer
    mailer_host: '%env(MAILER_HOST)%'
    mailer_user: '%env(MAILER_USER)%'
    mailer_password: '%env(MAILER_PASSWORD)%'

    # One of `legacy` (default) or `solr`
    search_engine: '%env(SEARCH_ENGINE)%'

    # Solr root endpoint, relevant if `solr` is set as search_engine
    solr_dsn: '%env(SOLR_DSN)%'
    solr_core: '%env(SOLR_CORE)%'

    # Log path, where to store the log files. php://stderr may be used in order to log to standard error
    log_path: '%env(LOG_PATH)%'

    # Settings for Cache pool, to change add own cache service and optionally inject own arguments
    # predefined pools: see symfony config and the optional pools in app/config/cache_pool/
    cache_pool: '%env(CACHE_POOL)%'

    # Cache DSN, see app/config/services/cache.yml for examples:
    cache_dsn: '%env(CACHE_DSN)%'
    
    # Cache namespace prefix for use with Redis/Memcached, 'ez' by default. 
    # For further info incl alternatives for "blue/green deployment" and multi repo installs, see: app/config/cache_pool/*.yml
    cache_namespace: '%env(CACHE_NAMESPACE)%'

    # Settings for HttpCache
    purge_server: '%env(HTTPCACHE_PURGE_SERVER)%'

    # By default cache ttl is set to 24h, when using Varnish you can set a much higher value. High values depends on
    # using EzSystemsPlatformHttpCacheBundle (default as of v1.12) which by design expires affected cache on changes
    httpcache_default_ttl: '%env(HTTPCACHE_DEFAULT_TTL)%'

    # Session save path as used by symfony session handlers (eg. used for dsn with redis)
    ezplatform.session.save_path: '%env(SESSION_SAVE_PATH)%'

    # Recommendation Bundle params
    ez_recommendation.default.yoochoose.customer_id: '%env(RECOMMENDATIONS_CUSTOMER_ID)%'
    ez_recommendation.default.yoochoose.license_key: '%env(RECOMMENDATIONS_LICENSE_KEY)%'
    ez_recommendation.default.server_uri: '%env(PUBLIC_SERVER_URI)%'

    # Fallback values for when environment variables do not exist

    env(MAILER_HOST):       127.0.0.1
    env(MAILER_USER):       ~
    env(MAILER_PASSWORD):   ~

    env(SEARCH_ENGINE): legacy

    env(SOLR_DSN): http://localhost:8983/solr
    env(SOLR_CORE): collection1

    env(LOG_PATH): "%kernel.logs_dir%/%kernel.environment%.log"

    # NOTE: For Windows usage you can use Symfony's `cache.app`, for eZ provided services see: app/config/cache_pool/*
    env(CACHE_POOL): "cache.tagaware.filesystem"

    env(CACHE_DSN): localhost

    env(CACHE_NAMESPACE): ez

    env(HTTPCACHE_PURGE_SERVER): "http://localhost:80"

    env(HTTPCACHE_DEFAULT_TTL): 86400

    env(SESSION_SAVE_PATH): '%kernel.project_dir%/var/sessions/%kernel.environment%'

    env(RECOMMENDATIONS_CUSTOMER_ID):   ~
    env(RECOMMENDATIONS_LICENSE_KEY):   ~
    env(PUBLIC_SERVER_URI):             ~

    # set here for BC reasons, change them in parameters.yml
    env(DATABASE_CHARSET): utf8mb4
    env(DATABASE_COLLATION): utf8mb4_unicode_520_ci
    env(DATABASE_VERSION): mariadb-10.2.26

    # Compile time handlers
    ## These are defined at compile time, and hence can't be set at runtime using env()
    ## app/config/env/generic.php takes care about letting you set them by env variables

    ## Log type is one of "stream", "error_log" or other types supported by monolog
    # env: LOG_TYPE
    log_type: stream

    ## Mail transport used by SwiftMailer
    # env: MAILER_TRANSPORT
    mailer_transport:  smtp

    ## Purge type used by HttpCache system ("local", "varnish"/"http", and on ee also "fastly")
    # env: HTTPCACHE_PURGE_TYPE
    purge_type: local

    ## Session handler, by default set to file based (instead of ~) in order to be able to use %ezplatform.session.save_path%
    # env: SESSION_HANDLER_ID
    ezplatform.session.handler_id: session.handler.native_file

    # Admin siteaccess group name
    admin_group_name: admin_group

    # Varnish invalidation/purge token (for use on platform.sh, eZ Platform Cloud and other places you can't use IP for ACL)
    varnish_invalidate_token: '%env(HTTPCACHE_VARNISH_INVALIDATE_TOKEN)%'
    env(HTTPCACHE_VARNISH_INVALIDATE_TOKEN): ~
    
    # LiipImagineBundle - imagine driver
    liip_imagine_driver: 'gd'
