# This file contains defaults for optional parameters, which you can override in parameters.yml
parameters:
    locale_fallback: en

    # Setting for mail system, used by SwiftMailer
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    # One of `legacy` (default) or `solr`
    search_engine: legacy

    # Solr root endpoint, relevant if `solr` is set as search_engine
    solr_dsn: http://localhost:8983/solr

    ## Logging settings
    # Log type is one of "stream", "error_log" or other types supported by monolog
    log_type: stream

    # Log path, where to store the log files. php://stderr may be used in order to log to standard error
    log_path: "%kernel.logs_dir%/%kernel.environment%.log"

    # Settings for Cache pool, to create your own pool see cache/ folder.
    cache_pool: "app.cache"
