imports:
    - { resource: ezplatform.yml }

ezpublish:
    siteaccess:
        list: ["site", "other_site"]
        groups:
            site_group: ["site", "other_site"]
        default_siteaccess: "site"
        match:
            URIElement: 1

ezdesign:
    phpstorm:
        enabled: false

ez_platform_standard_design:
    # for pre eZ Design Engine tests use old template naming
    override_kernel_templates: false

parameters:
    ezsettings.default.notifications.success.timeout: 20000
