login:
    path:   /login
    defaults:  { _controller: ezpublish.security.controller:loginAction }
login_check:
    path:   /login_check
logout:
    path:   /logout

_ezpublishRoutes:
    resource: "@EzPublishCoreBundle/Resources/config/routing/internal.yml"

_ezpublishRestRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix:   "%ezpublish_rest.path_prefix%"

_ezpublishRestOptionsRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix: "%ezpublish_rest.path_prefix%"
    type: rest_options

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_ezpublishPlatformUIRoutes:
    resource: "@eZPlatformUIBundle/Resources/config/routing.yml"

_ezplatformRepositoryFormsRoutes:
    resource: "@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ez_hybrid_ui:
    resource: "@EzSystemsHybridPlatformUiBundle/Resources/config/routing.yml"
