login:
    path:   /login
    defaults:
        _controller: ezpublish.security.controller:loginAction

login_check:
    path:   /login_check

logout:
    path:   /logout

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: /api/ezp/v2

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: 'admin_group'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'
