e_z_publish_bundles_cook_book:
    resource: "@eZPublishBundlesCookBookBundle/Resources/config/routing.yml"
    prefix:   /

eZDemoBundle:
    resource: "@eZDemoBundle/Resources/config/routing.yml"

_ezpublishRoutes:
    resource: "@EzPublishCoreBundle/Resources/config/routing/internal.yml"

_ezpublishLegacyRoutes:
    resource: "@EzPublishLegacyBundle/Resources/config/routing.yml"

_ezpublishRestRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix:   /api/ezp/v2

_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_internal

