login:
    path:   /login
    defaults:
        _controller: ezpublish.security.controller:loginAction

login_check:
    path:   /login_check

logout:
    path:   /logout

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: /api/ezp/v2

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: 'admin_group'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'

ezplatform.ee.dependencies.bazinga:
    resource: '@BazingaJsTranslationBundle/Resources/config/routing/routing.yml'

ezplatform.ee.dependencies.platform_ui:
    resource: '@eZPlatformUIBundle/Resources/config/routing.yml'

ezplatform.ee.admin_ui:
    resource: '@eZStudioUIBundle/Resources/config/routing.yml'

ezplatform.ee.form_builder:
    resource: '@EzSystemsFormBuilderBundle/Resources/config/routing.yml'

ezplatform.ee.date_based_publisher:
    resource: '@EzSystemsDateBasedPublisherBundle/Resources/config/routing.yml'

ezplatform.ee.flex_workflow:
    resource: '@FlexWorkflowBundle/Resources/config/routing.yml'

ezplatform.ee.notifications:
    resource: '@NotificationBundle/Resources/config/routing.yml'

ezplatform.ee.landing_page:
    resource: '@EzSystemsLandingPageFieldTypeBundle/Resources/config/routing.yml'

fos.js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'
