login:
    path: /login
    defaults: { _controller: ezpublish.security.controller:loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: /api/ezp/v2

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'

fos.js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

# Custom redirection from /ez to /admin, feel free to adjust to your needs or remove if you don't need it
platform1_admin_route:
    path: /ez
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true
