security:
    providers:
        ezpublish:
            id: ezpublish.security.user_provider
#!        in_memory:
#!            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        ## WARNING
        ## Until https://jira.ez.no/browse/EZP-22192 is implemented,
        ## enabling basic auth in RESTÂ will prevent PlatformUI from working
#        ezpublish_rest:
#            pattern: ^/api/ezp/v2
#            stateless: true
#            ezpublish_http_basic:
#                realm: eZ Publish REST API

        ezpublish_front:
            pattern: ^/
            anonymous: ~
            ezpublish_rest_session: ~
            form_login:
                require_previous_session: false
            logout: ~

        default:
            anonymous: ~
