# Optimized File cache adapter (from: https://github.com/ezsystems/symfony-tools)
#
# Loaded by default, for use on single server setups.
# If you are on Windows you would have to use `cache.app` by setting `env(CACHE_POOL): "cache.app"` parameter
services:
    cache.tagaware.filesystem:
        class: Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter
        parent: cache.adapter.filesystem
        tags:
            - name: cache.pool
              clearer: cache.app_clearer
              # Cache namespace prefix overriding the one used by Symfony by default
              # This makes sure cache is reliably shared across whole cluster and all Symfony env's
              # Can be used for blue/green deployment strategies when changes affect content cache.
              # For multi db setup adapt this to be unique per pool (one pool per database)
              # If you prefer default behaviour set this to null or comment out, and consider for instance:
              # https://symfony.com/doc/current/reference/configuration/framework.html#prefix-seed
              namespace: '%cache_namespace%'
