# Reusable service for memcache cache for use in generic.php and plaformsh.php on demand
services:
    cache.memcached:
        parent: cache.adapter.memcached
        tags:
            - name: cache.pool
              clearer: cache.app_clearer
              # Example from vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/MemcachedTrait.php:
              # memcached://user:pass@localhost?weight=33'
              provider: 'memcached://%cache_dsn%'
