mysqldb:
    type: mysql:10.2
    # Version 10.1 might be a better option when running Legacy Bridge
    # For more information see https://doc.ezplatform.com/en/2.1/getting_started/requirements_and_system_configuration/#supported-setups
    disk: 1024
    configuration:
        schemas:
            - main
            # Uncomment if you want to store dfs tables in a separate database:
            #- dfs
        endpoints:
            user:
                default_schema: main
                privileges:
                    main: admin
            # Uncomment if you want to store dfs tables in a separate database:
            #dfs:
            #    default_schema: dfs
            #    privileges:
            #        dfs: admin

# For use by Symfony Cache (used by eZ Platform SPI Persistence Cache)
rediscache:
    type: 'redis:3.2'

# If you wish to have a separate Redis instance for sessions, uncomment
# this service and the corresponding relationship in .platform.app.yaml.
#redissession:
#    type: 'redis:3.2'
#
# Alternatively if you have a requirement that sessions are persisted across server/redis restarts,
# have storage space to spare for this, and don't mind a bit slower instance type of redis
#redissession:
#    type: redis-persistent:3.2
#    disk: 512

# If you wish to use solr, uncomment this service and the corresponding relationship in .platform.app.yaml.
# Also, you need to generate the config using:
# vendor/ezsystems/ezplatform-solr-search-engine/bin/generate-solr-config.sh
# Multi core setup is currently not supported on Platform.sh. Sharding does not work as the cores are
# unable to reach each other
#solrsearch:
#    type: solr:6.6
#    disk: 512
#    configuration:
#        configsets:
#            mainconfig: !archive "configsets/solr6"
#        cores:
#            collection1:
#                core_properties: |
#                    configSet=mainconfig
#                    schema=schema.xml
#        endpoints:
#            collection1:
#                core: collection1

# Due to logic in app/config/env/platformsh.php, do not change the service name to something different than 'varnish'
varnish:
    type: 'varnish:6.0'
    relationships:
        app: "app:http"
    configuration:
        vcl: !include
            type: string
            path: varnish.vcl
