version: '3.3'
# Appends services to prod.yml, prod+dev, prod+redis, ..., always latest

services:
  selenium:
    image: ${SELENIUM_IMAGE}
    ports:
     - "9999:9999"
     - "4444:4444"
    environment:
     - SCREEN_WIDTH=1920
     - SCREEN_HEIGHT=1080
     - SCREEN_DEPTH=24
    networks:
     - backend

  app:
    depends_on:
     - selenium
    environment:
     - EZP_TEST_REST_HOST=$WEB_HOST
     - BEHAT_SELENIUM_HOST=$SELENIUM_HOST
     - BEHAT_WEB_HOST=$WEB_HOST
