version: '3.3'
# Single server setup for dev

services:
  app:
    image: ${PHP_IMAGE}
    volumes:
     - ${COMPOSE_DIR}/../../:/var/www:cached
     - ${COMPOSER_HOME}:/root/.composer:cached
    depends_on:
     - db
    environment:
     - COMPOSER_MEMORY_LIMIT
     - EZPLATFORM_SITEACCESS
     - PHP_INI_ENV_memory_limit
     - APP_ENV=${APP_ENV-dev}
     - APP_DEBUG
     - APP_HTTP_CACHE
     - TRUSTED_PROXIES
     - DATABASE_USER
     - DATABASE_PASSWORD
     - DATABASE_NAME
     - DATABASE_HOST=db
     - DATABASE_VERSION
     - RECOMMENDATIONS_CUSTOMER_ID
     - RECOMMENDATIONS_LICENSE_KEY
     - PUBLIC_SERVER_URI
     - HTTPCACHE_VARNISH_INVALIDATE_TOKEN
    networks:
     - backend

  web:
    image: ${NGINX_IMAGE}
    volumes:
     - ${COMPOSE_DIR}/../../:/var/www:ro,cached
    depends_on:
     - app
    ports:
     - "8080:80"
    environment:
     - APP_ENV=${APP_ENV-dev}
     - MAX_BODY_SIZE=20
     - FASTCGI_PASS=app:9000
     - TIMEOUT=190
    command: /bin/bash -c "cd /var/www && cp -a doc/nginx/ez_params.d /etc/nginx && bin/vhost.sh --basedir=/var/www --template-file=doc/nginx/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
     - frontend
     - backend

  db:
    image: ${MYSQL_IMAGE}
    volumes:
     - ${COMPOSE_DIR}/entrypoint/mysql:/docker-entrypoint-initdb.d/:ro,cached
    environment:
     - MYSQL_RANDOM_ROOT_PASSWORD=1
     - MYSQL_USER=$DATABASE_USER
     - MYSQL_PASSWORD=$DATABASE_PASSWORD
     - MYSQL_DATABASE=$DATABASE_NAME
     - TERM=dumb
    networks:
     - backend

networks:
  frontend:
  backend:
