version: '3.3'
# compose file for installing composer packages

services:
  install_dependencies:
    image: ${PHP_IMAGE_DEV}
    volumes:
     - ${COMPOSE_DIR}/../..:/var/www:cached
     - ${COMPOSER_HOME}:/root/.composer:cached
    environment:
     - COMPOSER_MEMORY_LIMIT
     - APP_ENV=${APP_ENV-prod}
     - APP_DEBUG
     - APP_CMD
     - DATABASE_VERSION
     - DATABASE_USER
     - DATABASE_PASSWORD
     - DATABASE_NAME
     - COMPOSER_AUTH
     - DATABASE_PLATFORM
     - DATABASE_PORT
    command: ./doc/docker/install_script.sh
